{% set goname = "github.com/golang/dep" %}
{% set version = "0.5.1" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/", "\\" if win else "/") %}

package:
  name: go-{{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz  # [unix]
    sha256: 720752ee3a089a8c6ee6a8ebecc7c70881bf2d994d3183d192a588398484b8d4  # [unix]
    git_url: https://{{ goname }}  # [win]
    git_tag: v{{ version }}  # [win]

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - 'go install -v -ldflags="-X main.version=v{{ version }}" ./cmd/dep'

requirements:
  build:
    - {{ compiler("go") }} >=1.11.3

test:
  requires:         # [win]
    - m2-coreutils  # [win]
  commands:
    - test -x {{target_gobin}}dep{{target_goexe}}
    - dep version

about:
  home: https://golang.github.io/dep/
  license: BSD-3-Clause
  license_file: {{ pkg_src }}/LICENSE
  summary: The Go dependency management tool
  doc_url: https://golang.github.io/dep/docs/introduction.html
  dev_url: https://{{ goname }}

extra:
  recipe-maintainers:
    - sodre
