travis:
  secure:
    BINSTAR_TOKEN: m2iZNtWZlvoHKos8MmaYp4/T0wMrdkVdVIwFBFwekeJKasecrDXDWSVTjgjJU5AZnWwIayPev09jCwyEUSRdhZ5WnUe+CskMbM865YMJbSuCpgPCz40FsK1J8SskECchKDstVzxSmN7AKD4v+59/FGkx+i4vERMmmr7azuUF5AdR8+9e0AwXGGkaHePH1aqXso20k7s4uipapQSNXtqXwwCw+SyJCHtaWtM3O2boYYTRTrgzxpOXU+SyhpyCbXqcBemRLkDoc1trISnCoiZVSVdO156SufXAARXlEdUr4dxn4EFPToIrOnQZUwwZocexJDBeht+2rxck2YqJdXQ3HRtyL2LezGnjBEZpUlN/JNnRhl9OZcJ1n/0PjtmT7HmmIFeeLjYV6EuBILXfBH03jPvJTFt8rgGh0YroZ/qvqrKiIzBEvanMTGzz++qR2AYL464mSH1DBlRkDX7t65NBLEXAJuMhMlH9bKX2F0pJv2zBFveWqQocFdRNOjHs63MXdiGdb3qSpZpJuvJu7oDWOyHWOEARjZU2tNy0R6pGBXitCpPxemHMUqZF9Uly0WNDZV1XjsumtTMVJybBKzDZ6QnYK0ptWi8i83rSBJHqz+Nt8cjTihdw0NH/mRqjQNTV1baRSpW2W39k12uTs6MZqpucQyWroDMzv/efqYW0exA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
